version: '3'
services:
  koyomi:
    container_name: "koyomi"
    image: "koyomi"
    restart: always
    volumes:
      - /home/user/python/discordbots/KoyomiBot/koyomibot/logs:/opt/koyomibot/logs/
      - /home/user/python/discordbots/KoyomiBot/koyomibot/config:/opt/koyomibot/config/
    depends_on:
      - "redis"
      - "mongo"
    dns:
      - 8.8.8.8

  redis:
    image: "redis:alpine"
    restart: always

  mongo:
    image: "mongo:latest"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /home/user/python/discordbots/KoyomiBot/db:/data/db
